#!/bin/sh
#
# Run all linting tools.
#

set -euC
regopherdir=$(cd -P "$(dirname "$0")/.." > /dev/null && pwd)
cd "$regopherdir"

### Setup Vim and other dependencies.
#####################################
if [ -z "${1:-}" ]; then
  echo "unknown version: '${1:-}'"
  echo "First argument must be 'vim-7.4', 'vim-8.0', or 'nvim'."
	exit 1
fi

vim=$1
vimdir="/tmp/regopher-test/$vim-install"
export GOPATH=$vimdir
export PATH=${GOPATH}/bin:$PATH

if [ ! -f "$vimdir/bin/vim" ]; then
	echo "$vimdir/bin/vim doesn't exist; did you install it with the install-vim script?"
	exit 1
fi

### Run vint
############
failed=0
printf "Running vint ... "
if [ -x "$(command -v vint)" ]; then
  lint=$(vint "$regopherdir" 2>&1 ||:)
  if [ -n "$lint" ]; then
    echo "FAILED"
    echo "$lint"
    echo
    failed=6
  else
    echo "PASSED"
  fi
else
  echo "SKIPPED"
  echo "'vint' binary not found; use 'pip install vim-vint' to install it."
fi

### Run vim-vimlint
###################
printf "Running vim-vimlint ... "
lint=$(sh "$vimdir/share/vim/regopher/pack/regopher/start/vim-vimlint/bin/vimlint.sh" \
  -p "$vimdir/share/vim/regopher/pack/regopher/start/vim-vimlparser" \
  -l "$vimdir/share/vim/regopher/pack/regopher/start/vim-vimlint" \
  -u \
  -c func_abort=1 \
  -e EVL110=1 -e EVL103=1 -e EVL104=1 -e EVL102=1 \
  "$regopherdir" \
  2>&1 ||:)
if [ -n "$lint" ]; then
  echo "FAILED"
  echo "$lint"
  echo
  failed=6
else
  echo "PASSED"
fi

### Run vimhelplint.
####################
printf "Running vimhelplint ... "

# set modeline explicitly so that the modeline will be respected when run as root.
lint=$($vimdir/bin/vim -esNR \
  --cmd "set rtp+=$vimdir/share/vim/regopher/pack/regopher/start/vim-vimhelplint/" \
  --cmd 'set modeline' \
  +'filetype plugin on' \
  +"e $regopherdir/doc/regopher.txt" \
  +'verbose VimhelpLintEcho' \
  +q \
  2>&1 ||:)
if [ "$lint" ]; then
  echo "FAILED"
  echo "$lint"
  failed=6
else
  echo "PASSED"
fi

exit "$failed"
